CREATE DATABASE IF NOT EXISTS webapi_demo
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE webapi_demo;

CREATE TABLE IF NOT EXISTS appliances (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sku VARCHAR(32) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  brand VARCHAR(80) NOT NULL,
  category VARCHAR(80) NOT NULL,
  price DECIMAL(10,2) NOT NULL CHECK (price >= 0),
  stock INT NOT NULL DEFAULT 0 CHECK (stock >= 0),
  warranty_months TINYINT UNSIGNED NOT NULL DEFAULT 12,
  energy_rating TINYINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);